### ISSUE TITLE
IFC Select classes should be generated

### ISSUE THREAD

**Issue by kurb70** [hypar-io/IFC-gen#38]
If I delete the generated C# files contained in the repository and regenerate them with `make csharp` (macOS), the Ifc…Select classes are not created.

The same happens when I regenerate the proto classes.

**Comment by ikeough** [comment]
Thanks for the update. Yes, I believe this is a problem that results from some refactoring I did to write the Selects separately. This was done to make select writing separate from the writing of other types for languages that support union types. I will investigate.
